services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Auxmoney\OpentracingBundleGuzzle\Middleware\GuzzleTracingHeaderInjection: ~
  Auxmoney\OpentracingBundleGuzzle\Middleware\GuzzleRequestSpanning: ~

  auxmoney_opentracing.guzzlehttp.default.handlerstack:
    class: GuzzleHttp\HandlerStack
    factory: ['GuzzleHttp\HandlerStack', 'create']
    calls:
      - [push, ['@Auxmoney\OpentracingBundleGuzzle\Middleware\GuzzleRequestSpanning']]
      - [push, ['@Auxmoney\OpentracingBundleGuzzle\Middleware\GuzzleTracingHeaderInjection']]
