services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Auxmoney\OpentracingGuzzleBundle\Middleware\GuzzleTracingHeaderInjection: ~
  Auxmoney\OpentracingGuzzleBundle\Middleware\GuzzleRequestSpanning: ~

  auxmoney_opentracing.guzzlehttp.default.handlerstack:
    class: GuzzleHttp\HandlerStack
    factory: ['GuzzleHttp\HandlerStack', 'create']
